Models/Cricket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Assesment_13.Models
{
    [Table("Cricket")]
    public class Cricket
    {
        [Key]
        public int TeamId { get; set; }
        public string TeamName { get; set; }
        public int NoWc { get; set; }


    }
}

Controllers/CricketController.cs
using Assesment_13.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assesment_13.Controllers
{
    public class CricketController : Controller
    {
        List<Cricket> listCricket = new List<Cricket>()
        {
            new Cricket() {TeamId=1,TeamName="India",NoWc=2},
            new Cricket() {TeamId=2,TeamName="Australia", NoWc=4},
            new Cricket() {TeamId=3,TeamName="West Indies", NoWc = 2},
            new Cricket() {TeamId=4,TeamName="England", NoWc = 1},

        };
        // GET: Cricket
        public ActionResult Index()
        {
            ViewData["Message"] = "Welcome to ICC Men's Cricket World Cup Qualifier ";

            ViewBag.noC = listCricket.Count;

            return View(listCricket);
        }

    }
}

Controllers/CricketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Assesment_13.Data;
using Assesment_13.Models;

namespace Assesment_13.Controllers
{
    public class CricketsController : Controller
    {
        private CricketDbContext db = new CricketDbContext();

        // GET: Crickets
        public ActionResult Index()
        {
            return View(db.Crickets.ToList());
        }

        // GET: Crickets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cricket cricket = db.Crickets.Find(id);
            if (cricket == null)
            {
                return HttpNotFound();
            }
            return View(cricket);
        }

        // GET: Crickets/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Crickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TeamId,TeamName,NoWc")] Cricket cricket)
        {
            if (ModelState.IsValid)
            {
                db.Crickets.Add(cricket);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cricket);
        }

        // GET: Crickets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cricket cricket = db.Crickets.Find(id);
            if (cricket == null)
            {
                return HttpNotFound();
            }
            return View(cricket);
        }

        // POST: Crickets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TeamId,TeamName,NoWc")] Cricket cricket)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cricket).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cricket);
        }

        // GET: Crickets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cricket cricket = db.Crickets.Find(id);
            if (cricket == null)
            {
                return HttpNotFound();
            }
            return View(cricket);
        }

        // POST: Crickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cricket cricket = db.Crickets.Find(id);
            db.Crickets.Remove(cricket);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assignment_13.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Views/Cricket/Index.cshtml
@model IEnumerable<Assesment_13.Models.Cricket>

@{
    ViewBag.Title = "Index";
}
<div class="jumbotron bg-black img-fluid">
    @{Html.RenderPartial("_CView");}
</div>
<h2>OurCricWebsite</h2>
<h2 class="bg-primary text-white text-center"> Number of Teams in Qualifier are: @ViewBag.noC</h2>
<h2 class="bg-warning text-dark text-center">@ViewData["Message"]</</h2>


<table class="table-bordered bg-warning text-dark text-center">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TeamId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TeamName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoWc)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TeamId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TeamName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoWc)
            </td>

        </tr>
    }

</table>

Views/Crickets/Create.cshtml
@model Assesment_13.Models.Cricket

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cricket</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TeamName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TeamName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TeamName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoWc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoWc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoWc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Crickets/Delete.cshtml
@model Assesment_13.Models.Cricket

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cricket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TeamName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeamName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoWc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoWc)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Crickets/Details.cshtml
@model Assesment_13.Models.Cricket

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Cricket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TeamName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeamName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoWc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoWc)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TeamId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Crickets/Edit.cshtml
@model Assesment_13.Models.Cricket

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cricket</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TeamId)

        <div class="form-group">
            @Html.LabelFor(model => model.TeamName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TeamName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TeamName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoWc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoWc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoWc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Crickets/Index.cshtml
@model IEnumerable<Assesment_13.Models.Cricket>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TeamName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoWc)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TeamName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NoWc)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.TeamId }) |
            @Html.ActionLink("Details", "Details", new { id=item.TeamId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.TeamId })
        </td>
    </tr>
}

</table>

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

Views/Shared/_CView.cshtml
<h2 class="text-center bg-primary text-white">Cricket Management System</h2>
<br />
<img src="~/Image/Logo.jpg" class="img-fluid" width="200" height="200" />

Views/Shared/_CricketLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title class="text-center">Cricket Info Web</title>

    <title>@ViewBag.Title - Cricket Management System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar bg-primary navabr-inverse navbar-fixed-top">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-gradient ">
            <div class="container">
                @Html.ActionLink("Cricket Management", "Index", "Home", new { area = "" }, new { @class = "navbar-brand bg-primary text-center" })
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="bg-primary text-white">@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li class="bg-primary text-white">@Html.ActionLink("Cricket", "Index", "Cricket", new { area = "" }, new { @class = "nav-link" })</li>
                        <li class="bg-primary text-white">@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li class="bg-primary text-white">@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="bg-primary text-white text-center">
            <p>&copy; @DateTime.Now.Year - Cricket Management System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cricket Management System </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Cricket Management", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="bg-primary text-white">@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="bg-primary text-white">@Html.ActionLink("Cricket", "Index", "Crickets", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="bg-primary text-white">@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="bg-primary text-white">@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>